"use strict";
exports.__esModule = true;
var Archivo_1 = require("./Archivo");
var Carpeta_1 = require("./Carpeta");
var carpeta1 = new Carpeta_1.Carpeta("carpeta_1");
var carpeta2 = new Carpeta_1.Carpeta("carpeta_2");
var carpeta3 = new Carpeta_1.Carpeta("carpeta_3");
var archivo1 = new Archivo_1.Archivo("archivo_1", 1, "txt");
var archivo2 = new Archivo_1.Archivo("archivo_2", 1, "txt");
var archivo3 = new Archivo_1.Archivo("archivo_3", 1, "txt");
var archivo4 = new Archivo_1.Archivo("archivo_4", 1, "txt");
var archivo5 = new Archivo_1.Archivo("archivo_5", 1, "txt");
var archivo6 = new Archivo_1.Archivo("archivo_6", 1, "txt");
carpeta1.agregarComponente(archivo1);
carpeta1.agregarComponente(carpeta2);
carpeta2.agregarComponente(archivo3);
carpeta2.agregarComponente(archivo4);
carpeta2.agregarComponente(archivo5);
carpeta2.agregarComponente(archivo6);
carpeta2.agregarComponente(carpeta3);
// console.log(carpeta1.obtenerNombre());
// console.log(carpeta1.obtenerPeso());
console.log(archivo3.obtenerDireccion());
